zcutlip/pyonepassword

README.md
pyonepassword/__about__.py
pyonepassword/pyonepassword.py

The library doesn't support file attachments right now.  Add a new `download` method to download items.

Add file support

---

pyonepassword/pyonepassword.py

Set OP_SESSION environment variable

---

pyonepassword/py_op_exceptions.py
pyonepassword/pyonepassword.py

This is a pretty naive implementation which just returns the decoded JSON dict from the response. I am absolutely open to taking another approach to it by creating native python objects to represent vault, group, user; I just went at it the most straightforward way I could think of.
I've tried to follow your conventions for error handling, but again I am open to critique.
I forked this in order to add in these features for some automation tasks, but given that your upstream is still under pretty active development, I figured it would be more sustainable to make the PR and coordinate with you on a proper implementation.

get_vault, get_group, get_user, list_event Implementation

---

.pre-commit-config.yaml
CHANGELOG.md

merge development into dev/support-item-creation-again

merge development into dev/support-item-creation-again

---

CHANGELOG.md
ipython_snippets/item_delete.py
pyonepassword/__about__.py
pyonepassword/_op_cli_argv.py
pyonepassword/_py_op_cli.py
pyonepassword/_py_op_commands.py
pyonepassword/api/exceptions.py
pyonepassword/py_op_exceptions.py
pyonepassword/pyonepassword.py
response-generation.cfg
tests/config/mock-op/response-directory.json
tests/config/mock-op/responses/item-delete-duplicate-titles/error_output
tests/config/mock-op/responses/item-delete-nonexistant-item/error_output
tests/config/mock-op/responses/item-get-archive-example-deleteme-include-archive/output
tests/config/mock-op/responses/item-get-archive-example-deleteme/output
tests/config/mock-op/responses/item-get-example-deleteme/output
tests/config/mock-op/responses/item-get-nonexistant-item/error_output
tests/config/mock-op/responses/item-list-vault-test-data-single-tag/output
tests/config/mock-op/responses/item-list-vault-test-data-two-tags/output
tests/data/expected-data/expected-item-data.json
tests/data/expected-data/expected-item-field-data.json
tests/data/expected-data/expected-item-section-data.json
tests/data/valid-data-registry.json
tests/fixtures/expected_login.py
tests/test_item_delete.py
tests/test_item_get/test_item_get_login.py
tests/test_item_get/test_item_get_totp.py

Add `OP.item_delete()` 
Closes #46

support item deletion

---

CHANGELOG.md
ITEM_CREATION.md
examples/item_creation/example-create-item-password-recipe.py
pyonepassword/__about__.py
pyonepassword/op_items/generic_item.py
pyonepassword/pyonepassword.py
tests/.gitignore

Merge development branch into main
- fixes #54

Merge development branch with fixes for #54

---

.github/workflows/python-package.yml
CHANGELOG.md
docker_testing/clean.sh
pyonepassword/__about__.py
setup.py
tox.ini

properly include all `pyonepassword` subpackages
clean *.egg-info before building/installing to ensure things are properly included/excluded, and tests catch missing items
update gh action workflow to target main & development branches & to run tox

merge development branch with fixes for #64

---

CHANGELOG.md

fix minor omission in CHANGELOG.md

merge development with minor update to CHANGELOG.md

---

.pre-commit-config.yaml
pyonepassword/__about__.py

set pre-commit.ci autoupdate_branch to "development"

merge development branch with config for pre-commit.ci

---

docker_testing/docker/test.sh
docker_testing/run.sh
pyonepassword/pyonepassword.py

fixes for #78, plus tweaks to docker testing scripts

#78 login_item_create crashes no url

---

pyonepassword/op_items/_new_item.py
pyonepassword/op_items/login.py
pyonepassword/pyonepassword.py

merge work-in-progress branch `dev/83-support-applying-tags-when-creating-items` into branch `development`

wip:#83 support applying tags when creating items

---

pyonepassword/api/object_types.py
pyonepassword/op_items/database.py

that's literally it, added the 1password database type
supports:
type,
server,
port,
database,
username,
password

added database type

---

CHANGELOG.md
pyonepassword/__about__.py
pyonepassword/_py_op_cli.py
pyonepassword/api/object_types.py
pyonepassword/op_items/_new_field_registry.py
pyonepassword/op_items/fields_sections/_new_fields.py
pyonepassword/op_items/item_types/database.py
pyonepassword/op_items/item_types/login.py
scripts/dump_all.py
tests/data/expected-data/expected-item-field-data.json
tests/data/test-input-data/valid-data-registry.json
tests/data/test-input-data/valid-data/example-database-1.json
tests/data/test-input-data/valid-data/example-database-2.json
tests/data/test-input-data/valid-data/item-field-network-port-int.json
tests/data/test-input-data/valid-data/item-field-network-port-str-hex.json
tests/data/test-input-data/valid-data/item-field-network-port-str.json
tests/fixtures/op_fixtures.py
tests/new_item/new_item_field/test_new_field_generate_uuid.py
tests/new_item/new_item_field/test_new_field_with_section.py
tests/new_item/new_item_field/test_new_network_port_field.py
tests/new_item/new_item_field/test_new_username_field.py
tests/new_item/test_new_database_item.py
tests/test_item_get/test_item_get_database.py

merge development into main

---

CHANGELOG.md
pyonepassword/__about__.py
pyonepassword/_op_cli_argv.py
pyonepassword/_py_op_commands.py
pyonepassword/account.py
pyonepassword/string.py
tests/test_redacted_string.py

merge `dev/130-sanitize-user-uuid-when-debug-logging` into `development` with changes for #130

issue #130 sanitize user UUID when debug logging

---

CHANGELOG.md
dev-reqs.txt
pyonepassword/__about__.py
pyonepassword/_op_cli_argv.py
scripts/batch_create.py

Merge development into main for issue #136

---

CHANGELOG.md
pyonepassword/op_items/fields_sections/item_field_base.py
pyonepassword/op_items/fields_sections/item_section.py
pyonepassword/op_items/item_types/_item_base.py
pyonepassword/op_items/item_types/server.py
tests/test_item_errors.py
tests/test_item_section.py

merge `144-make-field-section-lookup-more-robust` into `development` with changes for #144

issue #144 make field section lookup more robust

---

pyonepassword/op_items/_new_item.py

merge `dev/155-support-making-a-backup-of-new-item-templates-during-item-creation` into `development` with changes for #155

support optionally making backup copy of new item templates

---

CHANGELOG.md
pyonepassword/_py_op_commands.py
pyonepassword/py_op_exceptions.py
pyonepassword/pyonepassword.py
tests/test_auth_scenarios/test_existing_auth.py
tests/test_deprecation_warnings.py

merge `dev/161-remove-deprecated-items` into `development` with changes for #161

issue #161 remove deprecated items

---

docs/item-editing.md
pyonepassword/_op_cli_argv.py
pyonepassword/_py_op_commands.py
pyonepassword/pyonepassword.py
tests/config/mock-op/response-generation/item-edit/response-generation-item-edit-1.cfg
tests/config/mock-op/response-generation/item-edit/response-generation-item-edit-2.cfg
tests/test_item_edit/test_item_edit.py

merge `dev/164-reorganize-public-api-in-the-op-class` into `development` with changes for #164

issue #164 reorganize public api in the op class

---

.github/workflows/codeql.yml
CHANGELOG.md
pyonepassword/__about__.py
pyonepassword/pyonepassword.py
tests/config/mock-op/responses-item-edit/responses-2/item-get-example-login-21a/output
tests/config/mock-op/responses-item-edit/responses-2/item-get-example-login-21b/output
tests/config/mock-op/responses-item-edit/responses-2/item-get-example-login-23/output
tests/test_item_edit/test_item_edit_errors.py

Merge `development` into `main` for version 4.0.0, addressing issues #173

merge development into main: 4.0.1

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
pyonepassword/__about__.py

Merge `development` into `main` for version 4.2.0.post0
Minor updates to README and to .pre-commit-config.yaml

merge development into main: 4.2.0.post0

---

README.md
_readme_template.md
docker_testing/build.sh
docker_testing/clean.sh
docker_testing/run.sh
examples/item_creation/example-create-item.py
ipython_snippets/item_creation.py
pyonepassword/_op_cli_argv.py
pyonepassword/_op_commands.py
pyonepassword/_py_op_deprecation.py
pyonepassword/_svc_account.py
pyonepassword/op_items/_item_list.py
pyonepassword/op_items/_new_item.py
pyonepassword/pyonepassword.py
scripts/update_readme.py
setup.py
tests/new_item/test_new_database_item.py
tests/new_item/test_new_login_item.py

Merge `dev/172-create-new-items-via-stdin-to-op-command` into `development` with changes for #172

issue #172 create new items via stdin to op command
